## 소비분석 데이터 전처리


- 1번 데이터 셋과 범주 종류 같은지 확인
- 카테고리 변경사항 확인 필요한 열들
    - 가구소득
    - 혼인상태
    - 출생년도(나이 구하는 공식(각각의 년도 - 출생년도 + 1), 범주화(15세 미만 삭제))


- 열 선택, 이름 변경
- 기본 feature 무응답 확인 후 제거
- 18년 20년 병합

In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity="all"

In [2]:
import pandas as pd
import numpy as np

### 데이터 로드

In [3]:
CS2018_raw = pd.read_csv('../raw_data/소비분석2018.csv', encoding='euc-kr')
CS2020_raw = pd.read_csv('../raw_data/소비분석2020.csv', encoding='euc-kr')

In [4]:
CS2018_raw.head(1)
CS2020_raw.head(1)

ID  DE1  DE2  DE3  DE4  DE5  DE6  DE7  DE8  DE9  ...  ADQ3_2A1  ADQ3_2A2  \
0  529    1    6    2    6    1  140    1  140    2  ...      10.0       0.0   

   ADQ3_3A1  ADQ3_3A2  ADQ3_4  ADQ3_5  ADQ3_6  ADQ3_6A       wtb1     wtb2  
0      20.0       0.0     1.0     4.0    11.0      NaN  75.729294  0.37627  

[1 rows x 199 columns]

date  ID   GU  NUM_1  FAM15  HOUSE  LIFE  SQ1_1  SQ1_2  SQ1_3  ...  \
0  20211101   2  110      4      4      1     1      1      1   1960  ...   

      wtb1   wtb2  DEW1  DEW2  DEW3  DEW4  DEW5   DEW6  DEW7  DEW8  
0  132.431  0.654   1.0   6.0   2.0   6.0   1.0  110.0   1.0   3.0  

[1 rows x 189 columns]

In [5]:
CS2018_raw.shape
CS2020_raw.shape

(42991, 199)

(40085, 189)

### 데이터 전처리

#### 필요있는 열만 추출, 이름 변경

- 성별
- 학력별
- 소득별
- 혼인상태별
- 고용형태별
- 출생년도
- 문11. 문화 활동_연간총비용1) 전시회 관람
- 문11. 문화 활동_연간총비용1) 박물관관람
- 문11. 문화 활동_연간총비용1) 음악 및 무용 발표회 관람
- 문11. 문화 활동_연간총비용1) 전통예술공연 관람
- 문11. 문화 활동_연간총비용1) 연극 공연 관람
- 문11. 문화 활동_연간총비용1) 극장에서 영화관람
- 문11. 문화 활동_연간총비용1) 대중공연 관람
- 문화 활동 연간 총비용 합계

#### 2018년 & 2020년 데이터 정리

In [6]:
CS2018_raw.columns

Index(['ID', 'DE1', 'DE2', 'DE3', 'DE4', 'DE5', 'DE6', 'DE7', 'DE8', 'DE9',
       ...
       'ADQ3_2A1', 'ADQ3_2A2', 'ADQ3_3A1', 'ADQ3_3A2', 'ADQ3_4', 'ADQ3_5',
       'ADQ3_6', 'ADQ3_6A', 'wtb1', 'wtb2'],
      dtype='object', length=199)

In [7]:
# 2018년 필요한 열 추출
CS2018 = CS2018_raw[['DE1', 'DE3', 'DE4', 'DE5', 'DE11', 'ABIR', 
                     'AQ11_1_2', 'AQ11_1_4', 'AQ11_1_6', 'AQ11_1_8',
                     'AQ11_1_10', 'AQ11_1_12', 'AQ11_1_14'
                    ]]

In [8]:
CS2018.head(1)

DE1  DE3  DE4  DE5  DE11  ABIR  AQ11_1_2  AQ11_1_4  AQ11_1_6  AQ11_1_8  \
0    1    2    6    1   4.0  1948       NaN       NaN       NaN       NaN   

   AQ11_1_10  AQ11_1_12  AQ11_1_14  
0        NaN        NaN        NaN

In [9]:
# 2020년 필요한 열 추출
CS2020 = CS2020_raw[['SQ1_2', 'ADQ1', 'ADQ3_5', 'SQ1_4',
                    'ADQ3_1', 'SQ1_3', 'AQ12B1', 'AQ12B2',
                    'AQ12B3', 'AQ12B4', 'AQ12B5', 'AQ12B6', 'AQ12B7'
                    ]]

In [10]:
CS2020.head(1)

SQ1_2  ADQ1  ADQ3_5  SQ1_4  ADQ3_1  SQ1_3  AQ12B1  AQ12B2  AQ12B3  AQ12B4  \
0      1     4    12.0      1     5.0   1960     NaN     NaN     NaN     NaN   

   AQ12B5  AQ12B6  AQ12B7  
0     NaN     NaN     NaN

In [11]:
CS2018 = CS2018[['DE1', 
                 'DE3', 
                 'DE4', 
                 'DE5', 
                 'DE11', 
                 'ABIR', 
                 'AQ11_1_2', 
                 'AQ11_1_4', 
                 'AQ11_1_6', 
                 'AQ11_1_8',
                 'AQ11_1_10', 
                 'AQ11_1_12', 
                 'AQ11_1_14',
                ]]

In [12]:
CS2018.columns = [
    'sex',
    'education',
    'income',
    'married',
    'work',
    'age',
    'exhibition_price',
    'museum_price',
    'art_price',
    'traditional_price',
    'theater_price',
    'movie_price',
    'performance_price',
]

In [13]:
CS2018.columns

Index(['sex', 'education', 'income', 'married', 'work', 'age',
       'exhibition_price', 'museum_price', 'art_price', 'traditional_price',
       'theater_price', 'movie_price', 'performance_price'],
      dtype='object')

In [14]:
CS2018.shape

(42991, 13)

In [15]:
CS2018.head()
CS2018.tail()

sex  education  income  married  work   age  exhibition_price  \
0    1          2       6        1   4.0  1948               NaN   
1    2          2       6        1   NaN  1948               NaN   
2    2          2       5        1   NaN  1956               NaN   
3    1          2       5        1   4.0  1950               NaN   
4    1          3       6        1   3.0  1980               NaN   

   museum_price  art_price  traditional_price  theater_price  movie_price  \
0           NaN        NaN                NaN            NaN          NaN   
1           NaN        NaN                NaN            NaN          NaN   
2           NaN        NaN                NaN            NaN      30000.0   
3           NaN        NaN                NaN            NaN          NaN   
4           NaN        NaN                NaN            NaN      30000.0   

   performance_price  
0                NaN  
1                NaN  
2                NaN  
3                NaN  
4                NaN

sex  education  income  married  work   age  exhibition_price  \
42986    1          2       1        3   2.0  1956               NaN   
42987    2          1       4        1   2.0  1956               NaN   
42988    1          2       4        1   4.0  1960               NaN   
42989    2          2       5        1   2.0  1974               NaN   
42990    1          3       5        1   1.0  1974               NaN   

       museum_price  art_price  traditional_price  theater_price  movie_price  \
42986           NaN        NaN                NaN            NaN          NaN   
42987           NaN        NaN                NaN            NaN          NaN   
42988           NaN        NaN                NaN            NaN          NaN   
42989           0.0        NaN                0.0            NaN          0.0   
42990           NaN        NaN                NaN            NaN      50000.0   

       performance_price  
42986                NaN  
42987                NaN  
42988                NaN  
42989                NaN  
42990                NaN

In [16]:
CS2020 = CS2020[['SQ1_2', 
                 'ADQ1', 
                 'ADQ3_5', 
                 'SQ1_4',
                 'ADQ3_1', 
                 'SQ1_3', 
                 'AQ12B1', 
                 'AQ12B2',
                 'AQ12B3', 
                 'AQ12B4', 
                 'AQ12B5', 
                 'AQ12B6', 
                 'AQ12B7',
                ]]

In [17]:
CS2020.columns = [
    'sex',
    'education',
    'income',
    'married',
    'work',
    'age',
    'exhibition_price',
    'museum_price',
    'art_price',
    'traditional_price',
    'theater_price',
    'movie_price',
    'performance_price',
]

In [18]:
CS2020.columns

Index(['sex', 'education', 'income', 'married', 'work', 'age',
       'exhibition_price', 'museum_price', 'art_price', 'traditional_price',
       'theater_price', 'movie_price', 'performance_price'],
      dtype='object')

In [19]:
CS2020.shape

(40085, 13)

#### 출생년도 범주화
- 15세 미만 삭제

In [20]:
# 출생년도 계산 후 열에 적용 - 2018
def cal_age_2018(values):
    age = 2018-values + 1
    return age 

CS2018['age'] = CS2018['age'].apply(cal_age_2018)
CS2018['age'].head(5)

0    71
1    71
2    63
3    69
4    39
Name: age, dtype: int64

In [21]:
# 출생년도 계산 후 열에 적용 - 2020
def cal_age_2020(values):
    age = 2020-values + 1
    return age 

CS2020['age'] = CS2020['age'].apply(cal_age_2020)
CS2020['age'].head(5)

0    61
1    59
2    26
3    38
4    17
Name: age, dtype: int64

In [22]:
# 15세 미만 삭제 - 15세 미만 없음
CS2018[CS2018.age < 15]
CS2020[CS2020.age < 15]

Empty DataFrame
Columns: [sex, education, income, married, work, age, exhibition_price, museum_price, art_price, traditional_price, theater_price, movie_price, performance_price]
Index: []

Empty DataFrame
Columns: [sex, education, income, married, work, age, exhibition_price, museum_price, art_price, traditional_price, theater_price, movie_price, performance_price]
Index: []

In [23]:
# 출생년도 범주화 함수
def age_ctg(values):
    # 15-19세 (15세는 없으므로 19세 이하로 범주화)
    if values <= 19:
        return 1
    # 20대
    elif values > 19 and values <= 29:
        return 2
    # 30대
    elif values > 29 and values <= 39:
        return 3
    # 40대
    elif values > 39 and values <= 49:
        return 4
    # 50대
    elif values > 49 and values <= 59:
        return 5
    # 60대
    elif values > 59 and values <= 69:
        return 6
    # 70대 이상
    else:
        return 7

In [24]:
# 출생년도 범주화
CS2018['age'] = CS2018['age'].apply(age_ctg)
CS2018['age'].head(5)

CS2020['age'] = CS2020['age'].apply(age_ctg)
CS2020['age'].head(5)

0    7
1    7
2    6
3    6
4    3
Name: age, dtype: int64

0    6
1    5
2    2
3    3
4    1
Name: age, dtype: int64

### NA값 처리 - 범주형

In [25]:
CS2018.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42991 entries, 0 to 42990
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sex                42991 non-null  int64  
 1   education          42991 non-null  int64  
 2   income             42991 non-null  int64  
 3   married            42991 non-null  int64  
 4   work               26108 non-null  float64
 5   age                42991 non-null  int64  
 6   exhibition_price   4179 non-null   float64
 7   museum_price       5606 non-null   float64
 8   art_price          1589 non-null   float64
 9   traditional_price  1772 non-null   float64
 10  theater_price      6536 non-null   float64
 11  movie_price        26964 non-null  float64
 12  performance_price  2453 non-null   float64
dtypes: float64(8), int64(5)
memory usage: 4.3 MB


In [26]:
CS2020.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40085 entries, 0 to 40084
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sex                40085 non-null  int64  
 1   education          40085 non-null  int64  
 2   income             27489 non-null  float64
 3   married            40085 non-null  int64  
 4   work               27489 non-null  float64
 5   age                40085 non-null  int64  
 6   exhibition_price   2666 non-null   float64
 7   museum_price       3520 non-null   float64
 8   art_price          8465 non-null   float64
 9   traditional_price  24967 non-null  float64
 10  theater_price      7118 non-null   float64
 11  movie_price        7145 non-null   float64
 12  performance_price  4100 non-null   float64
dtypes: float64(9), int64(4)
memory usage: 4.0 MB


In [27]:
CS2018.isna().sum()

sex                      0
education                0
income                   0
married                  0
work                 16883
age                      0
exhibition_price     38812
museum_price         37385
art_price            41402
traditional_price    41219
theater_price        36455
movie_price          16027
performance_price    40538
dtype: int64

In [28]:
CS2020.isna().sum()

sex                      0
education                0
income               12596
married                  0
work                 12596
age                      0
exhibition_price     37419
museum_price         36565
art_price            31620
traditional_price    15118
theater_price        32967
movie_price          32940
performance_price    35985
dtype: int64

#### 2018  범주형 결측치 제거
- work

In [29]:
CS2018 = CS2018[CS2018.work.notnull()]

In [30]:
CS2018.isna().sum() # 범주형 변수 결측치 처리 완료

sex                      0
education                0
income                   0
married                  0
work                     0
age                      0
exhibition_price     23696
museum_price         22966
art_price            25106
traditional_price    25174
theater_price        21865
movie_price           8860
performance_price    24563
dtype: int64

#### 2020  범주형 결측치 제거
- income
- work

In [31]:
CS2020 = CS2020[CS2020.income.notnull()]
CS2020 = CS2020[CS2020.work.notnull()]

In [32]:
CS2020.isna().sum() 

sex                      0
education                0
income                   0
married                  0
work                     0
age                      0
exhibition_price     25521
museum_price         24713
art_price            21142
traditional_price     9651
theater_price        22199
movie_price          22342
performance_price    24307
dtype: int64

### 범주형 데이터의 코드값 통일

In [33]:
# 코드 통일이 필요한 열 이름
need_setting_columns = [
    'education',
    'income',
    'married',
    'work',
    
]

In [34]:
# 코드값 통일이 필요한 열들의
# 통일 전 카테고리 출력

# 2018년 work, 2020년 work 코드값 실수형

print('2018년')
for column in need_setting_columns:
    CS2018[column].value_counts().sort_index()
    
print('2020년')
for column in need_setting_columns:
    CS2020[column].value_counts().sort_index()

2018년


1     1076
2     8380
3    16258
4      394
Name: education, dtype: int64

1      122
2      920
3     2590
4     4512
5     5150
6    12814
Name: income, dtype: int64

1    18551
2     5237
3     1358
5      952
6       10
Name: married, dtype: int64

1.0    18535
2.0     2819
3.0     2987
4.0     1463
5.0      304
Name: work, dtype: int64

2020년


1        5
2      154
3      492
4     5948
5     4141
6    14441
7     2308
Name: education, dtype: int64

1.0      510
2.0      589
3.0     1202
4.0     2610
5.0     4509
6.0     3902
7.0     4396
8.0     2428
9.0     2120
10.0    1163
11.0    1128
12.0     557
13.0     538
14.0     290
15.0     338
16.0     201
17.0     248
18.0     415
19.0     345
Name: income, dtype: int64

1    19644
2     5844
3      988
4      106
5      902
6        5
Name: married, dtype: int64

1.0    19520
2.0     2664
3.0      599
4.0      719
5.0     1215
6.0     2521
7.0      251
Name: work, dtype: int64

In [35]:
#  결측치 제거 후 코드값 확인
CS2018.education.unique()
CS2018.income.unique()
CS2018.married.unique()
CS2018.work.unique()

CS2020.education.unique()
CS2020.income.unique()
CS2020.married.unique()
CS2020.work.unique()

array([2, 3, 1, 4], dtype=int64)

array([6, 5, 4, 3, 1, 2], dtype=int64)

array([1, 5, 3, 2, 6], dtype=int64)

array([4., 3., 5., 1., 2.])

array([4, 5, 6, 3, 2, 7, 1], dtype=int64)

array([12.,  8.,  7., 11.,  9.,  6., 14.,  5.,  4.,  1., 17.,  3., 16.,
       18., 13., 15., 10.,  2., 19.])

array([1, 5, 2, 3, 4, 6], dtype=int64)

array([5., 1., 6., 2., 7., 4., 3.])

In [36]:
# '코드값 변경 이전 : 이후 딕셔너리'를 포함한 리스트 2018년 

setting_codes_2018 = [
    # education
    {
        1 : 2,
        2 : 3,
        3 : 4,
        4 : 4,
    },
    # income
    {
        1 : 1,
        2 : 1,
        3 : 3,
        4 : 4,
        5 : 5,
        6 : 6,

    },
    # married
    {
        2 : 1,
        6 : 1,
        1 : 2,
        3 : 3,
        5 : 3,
    },
    
    # work
    {
        1.0 : 1,
        2.0 : 1,
        4.0 : 2,
        3.0 : 3,
        5.0 : 4,
    },
]

# work 코드값 실수형, 6번 코드에 해당하는 값 없음

In [37]:
# '코드값 변경 이전 : 이후 딕셔너리'를 포함한 리스트 2020년 

setting_codes_2020 = [
    # education
    {
        1 : 1,
        2 : 1,
        3 : 2,
        4 : 3,
        5 : 4,
        6 : 4,
        7 : 4,
    },
    # income
    {
        1 : 1,
        2 : 1,
        3 : 2,
        4 : 2,
        5 : 3,
        6 : 3,
        7 : 4,
        8 : 4,
        9 : 5,
        10 : 5,
        11 : 6,
        12 : 6,
        13 : 7,
        14 : 7,
        15 : 7,
        16 : 7,
        17 : 7,
        18 : 7,
        19 : 7,
    },
    # married
    {
        2 : 1,
        6 : 1,
        1 : 2,
        3 : 3,
        4 : 3,
        5 : 3,
    },
    
    # work
    {
        1.0 : 1,
        2.0 : 1,
        3.0 : 1,
        4.0 : 1,
        5.0 : 2,
        6.0 : 3,
        7.0 : 4,
    },
]

# work 코드값 실수형

In [38]:
# 코드 통일 함수 선언
def get_list_setting_column(column, setting_prev_next):
    setting_done_list = []
    
    for code_value in column:
        setting_done_list.append(setting_prev_next[code_value])
    
    return setting_done_list

In [39]:
# 코드 통일이 필요한 모든 열에 대해 코드 통일
for i, column in enumerate(need_setting_columns):
   
    CS2018[column] = get_list_setting_column(CS2018[column], setting_codes_2018[i])
    
    CS2020[column] = get_list_setting_column(CS2020[column], setting_codes_2020[i])

In [40]:
# 코드값 통일이 필요한 열들의
# 통일 후 카테고리 출력
print('2018년')
for column in need_setting_columns:
    CS2018[column].value_counts().sort_index()
    
print('2020년')
for column in need_setting_columns:
    CS2020[column].value_counts().sort_index()

2018년


2     1076
3     8380
4    16652
Name: education, dtype: int64

1     1042
3     2590
4     4512
5     5150
6    12814
Name: income, dtype: int64

1     5247
2    18551
3     2310
Name: married, dtype: int64

1    21354
2     1463
3     2987
4      304
Name: work, dtype: int64

2020년


1      159
2      492
3     5948
4    20890
Name: education, dtype: int64

1    1099
2    3812
3    8411
4    6824
5    3283
6    1685
7    2375
Name: income, dtype: int64

1     5849
2    19644
3     1996
Name: married, dtype: int64

1    23502
2     1215
3     2521
4      251
Name: work, dtype: int64

### 파생변수 생성
- 문화 활동 연간 총비용 합계 : total_price 

In [41]:
CS2018.iloc[:, 6:].head(5)
CS2020.iloc[:, 6:].head(1)

exhibition_price  museum_price  art_price  traditional_price  \
0               NaN           NaN        NaN                NaN   
3               NaN           NaN        NaN                NaN   
4               NaN           NaN        NaN                NaN   
5           40000.0           0.0    50000.0                NaN   
6               0.0           NaN        NaN                NaN   

   theater_price  movie_price  performance_price  
0            NaN          NaN                NaN  
3            NaN          NaN                NaN  
4            NaN      30000.0                NaN  
5            NaN      20000.0                NaN  
6            NaN      50000.0                NaN

exhibition_price  museum_price  art_price  traditional_price  \
0               NaN           NaN        NaN                NaN   

   theater_price  movie_price  performance_price  
0            NaN          NaN                NaN

In [42]:
CS2018['total_price'] = CS2018.iloc[:, 6:].apply(np.sum, axis=1).astype(int)
CS2020['total_price'] = CS2020.iloc[:, 6:].apply(np.sum, axis=1).astype(int)

In [43]:
CS2018[['total_price']]
CS2020[['total_price']]

total_price
0                0
3                0
4            30000
5           110000
6            50000
...            ...
42986            0
42987            0
42988            0
42989            0
42990        50000

[26108 rows x 1 columns]

total_price
0                0
3            30000
6                0
7           120000
10               0
...            ...
40080       255000
40081       832000
40082       470000
40083       250000
40084        10000

[27489 rows x 1 columns]

### 데이터 병합
- 2018 & 2020 데이터 병합

In [44]:
# shape 확인
CS2018.shape
CS2020.shape

(26108, 14)

(27489, 14)

In [45]:
CS = pd.concat([CS2018, CS2020], axis=0, ignore_index=True)

In [46]:
CS.info()
# 각각의 문화 활동 float 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53597 entries, 0 to 53596
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sex                53597 non-null  int64  
 1   education          53597 non-null  int64  
 2   income             53597 non-null  int64  
 3   married            53597 non-null  int64  
 4   work               53597 non-null  int64  
 5   age                53597 non-null  int64  
 6   exhibition_price   4380 non-null   float64
 7   museum_price       5918 non-null   float64
 8   art_price          7349 non-null   float64
 9   traditional_price  18772 non-null  float64
 10  theater_price      9533 non-null   float64
 11  movie_price        22395 non-null  float64
 12  performance_price  4727 non-null   float64
 13  total_price        53597 non-null  int32  
dtypes: float64(7), int32(1), int64(6)
memory usage: 5.5 MB


### CSV로 저장

In [50]:
CS.to_csv('../data/소비분석.csv', index=False)